---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: self-signed-issuer
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: own-ca-issuer
spec:
  ca:
    secretName: own-ca-secret

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: own-ca
spec:
  isCA: true
  commonName: own-ca
  secretName: own-ca-secret
  issuerRef:
    name: self-signed-issuer
    kind: ClusterIssuer
    group: cert-manager.io
