---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-srv
  labels:
    app: {{ .Chart.Name }}
    version: {{ .Chart.AppVersion }}
    {{ toYaml .Values.labels }}
spec:
  selector:
    app: {{ .Chart.Name }} #1
    version: {{ .Chart.AppVersion }}
  ports:
    {{- range .Values.service.ports }}
    - protocol: {{ default "TCP" .protocol }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      {{- if eq $.Values.service.type "nodePort" }}
      nodePort: {{ .nodePort }}
      {{- end }}
    {{- end }}
  type: {{ default "ClusterIP" .Values.service.type  }}
