network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s3:
      dhcp4: no
      addresses:
        - 10.5.10.109/24
      routes:
        - to: default
          via: 10.5.10.254
      nameservers:
        addresses: [8.8.8.8]