---
stages:
  - build
  - test
  - push

variables:
  REGISTRY_IP: 192.168.1.16

# services:
#   - docker:dind

docker-build-master:
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    # - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker build --pull -t "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/hello-go:latest" .
  after_script:
    - docker rm -f testing-go
  only:
    - main

docker-run-master:
  stage: test
  script:
    # - docker run --name=testing-go -p 8080:8080 -d "$CI_REGISTRY_IMAGE"
    - docker run --name=testing-go -p 8080:8080 -d "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/hello-go:latest"
  only:
    - main

docker-test-master:
  image: curlimages/curl:latest
  stage: test
  script:
    - curl http://$REGISTRY_IP:8080
  only:
    - main

docker-push-master:
  stage: push
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    # - docker push "$CI_REGISTRY_IMAGE"
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/hello-go:latest"
  after_script:
    - docker rm -f testing-go
  only:
    - main
